### PR TITLE
add twitch to players in ongoing matches

### PR DESCRIPTION
**Pull request by SergeyKhval**
This is a step needed to implement active streams on home page and may be on ongoing matches page
image

### CODE REVIEW

**Comment by modmoto** [comment]
This would be needed to show the twitch channel on the ongoing matches? Or do we need that for something else? The matches are now in memory, because they had performance issues.  The ongoing matches are about 1/6ths of our requests. Just make sure, that we do not get any problems when loading all the user settings everytime we go on the ongoing matches page.

**Comment by Cepheid-UK** [comment]
This supports https://github.com/w3champions/w3champions-ui/issues/279

**Comment by SergeyKhval** [comment]
I added UI part for this. I am going to deploy it to test and take a look at performance. Is it possible to use prod DB on test to check with realtime data?

**Comment by modmoto** [comment]
Yes we could, but I do not want to mess with the data on prod. We can just deploy and see what happens ;)

**Pull request merged**
