### PR TITLE
Fix MMRs being counted twice

### PR DESCRIPTION
**Pull request by alocate**
the math.abs(x-r) < 25 part is looking at intervals of length 50

### CODE REVIEW

**Comment by modmoto** [comment]
Did you check how that looks in the UI? It has been some time that I had a look at that, but would that not create half the mmr bars in the UI? Not so sure, that we do not have anything hard coded in the UI (e.g. the 25mmr steps).

**Comment by modmoto** [comment]
thanks for the PR though =D

**Comment by abeninski** [comment]
Yo Toxi adding first PR!

**Comment by modmoto** [comment]
ah that is toxi =D

**Comment by alocate** [comment]
now should be good without touching anything else =D?

**Pull request merged**
